# Generated by Django 6.0.5 on 2026-05-13 18:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Eleicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("1", "estudantil"),
                            ("2", "sindical"),
                            ("3", "associacao"),
                            ("4", "condominio"),
                            ("5", "conselho"),
                        ],
                        default="1",
                        max_length=1,
                    ),
                ),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "rascunho"),
                            ("2", "aberta"),
                            ("3", "encerrada"),
                            ("4", "apurada"),
                            ("5", "conselho"),
                        ],
                        default="1",
                        max_length=1,
                    ),
                ),
                ("permite_branco", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "Eleicoes",
                "ordering": ["titulo"],
            },
        ),
        migrations.CreateModel(
            name="Eleitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "cpf",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                ("data_nascimento", models.DateField()),
                ("ativo", models.BooleanField(default=True)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Eleitores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("nome", models.CharField(max_length=150)),
                ("nome_urna", models.CharField(max_length=50)),
                ("partido_chapa", models.CharField(blank=True, max_length=100)),
                ("proposta", models.TextField(blank=True)),
                ("foto_url", models.URLField(blank=True)),
                (
                    "eleicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatos",
                        to="backend.eleicao",
                    ),
                ),
            ],
            options={
                "db_table": "candidatos",
                "ordering": ["nome"],
                "unique_together": {("eleicao", "numero")},
            },
        ),
        migrations.AddField(
            model_name="eleicao",
            name="criada_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eleicoes_criadas",
                to="backend.eleitor",
            ),
        ),
        migrations.CreateModel(
            name="RegistroVotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "eleicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_votacao",
                        to="backend.eleicao",
                    ),
                ),
                (
                    "eleitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_votacao",
                        to="backend.eleitor",
                    ),
                ),
            ],
            options={
                "db_table": "registrovotacao",
            },
        ),
        migrations.CreateModel(
            name="Voto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("em_branco", models.BooleanField(default=False)),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("comprovante_hash", models.CharField(max_length=64, unique=True)),
                (
                    "candidato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votos",
                        to="backend.candidato",
                    ),
                ),
                (
                    "eleicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votos",
                        to="backend.eleicao",
                    ),
                ),
            ],
            options={
                "db_table": "votos",
                "ordering": ["eleicao"],
            },
        ),
        migrations.CreateModel(
            name="AptidaoLeitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inclusao", models.DateTimeField(auto_now_add=True)),
                (
                    "eleicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_aptos",
                        to="backend.eleicao",
                    ),
                ),
                (
                    "eleitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aptidoes",
                        to="backend.eleitor",
                    ),
                ),
            ],
            options={
                "db_table": "aptidaoleitor",
                "ordering": ["eleitor"],
                "unique_together": {("eleitor", "eleicao")},
            },
        ),
    ]
